### PR TITLE
CI: Remove dmd-2.087 from the matrix

### PR DESCRIPTION
**Pull request by PetarKirov**
As it it's not compatible with macos-latest.

### CODE REVIEW

**Comment by PetarKirov** [comment]
@burner Since GH Actions don't run in the context of the PR that adds them to the repo I was not able to verify that everything is green in #29. Now that it got merged, I saw that the macos-latest job with dmd 2.087 [fails](https://github.com/dlang-community/experimental.xml/actions/runs/965449107), hence I made this PR to fix the CI and now everything looks good. Support for old compilers can still be added in future PRs, but we just have to make sure that they don't break the CI.

**Comment by burner** [comment]
I'll take another look

**Comment by burner** [comment]
I was stupid and miss-typed 97 as 87 sorry for the noise

**Comment by PetarKirov** [comment]
No worries ;)

**Pull request merged**
