### PR TITLE
made it work with 2.097

### LINKED ISSUE #28: Error: module `std.traits` member `AliasSeq` is not visible from module `domimpl`
https://github.com/dlang-community/experimental.xml/blob/740bb6b05225a800b88cbffee33d0c1403f73a61/source/std/experimental/xml/domimpl.d#L174

This code invalid in dmd 2.097.0.
Use `import std.meta: AliasSeq;` instead.

### PR DESCRIPTION
**Pull request by burner**
Fixes #28

### CODE REVIEW

**Comment by PetarKirov** [comment]
Hey @burner thanks taking care of the issue! Unfortunately Travis CI is no more, so we need to replace it. I suggest using this: https://github.com/dlang-community/setup-dlang. Can you make the switch in this PR?

**Comment by burner** [comment]
I'll take a look. Thank you for letting me know

**Comment by burner** [comment]
I removed the .travis-ci stuff and added a github action to this PR

**Comment by PetarKirov** [comment]
Thanks, let's give it a try!

**Review by PetarKirov — APPROVED** [review]

**Comment by burner** [comment]
thank you

**Pull request merged**
